      character*10 cl_target
      REAL cl_beam_energy,cl_zpos,cl_zwidth
      integer cl_verblev,cl_rand,cl_nprint
      integer cl_triggers,cl_pol
      character*60 bosout
      common /OUT_NAMES/ bosout
      common /claspepsi1/ cl_verblev,cl_nprint,cl_rand
      common /claspepsi2/ cl_target
      common /claspepsi3/ cl_triggers,cl_beam_energy,cl_pol
      common /claspepsi4/ cl_zpos,cl_zwidth
